ALTER TABLE SCHEDULE ALTER ID NUMBER NOT NULL AUTO_INCREMENT;

ALTER TABLE CUSTOM_SCHEDULE ALTER ID NUMBER NOT NULL AUTO_INCREMENT;

ALTER TABLE PLOT ALTER ID NUMBER NOT NULL AUTO_INCREMENT;

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_RED_SOIL_AUTUMN', 'WHEAT_RED_SOIL_AUTUMN', 'WHEAT', 'RED_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_BLACK_SOIL_AUTUMN', 'WHEAT_BLACK_SOIL_AUTUMN', 'WHEAT', 'BLACK_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_ALLUVIAL_SOIL_AUTUMN', 'WHEAT_ALLUVIAL_SOIL_AUTUMN', 'WHEAT', 'ALLUVIAL_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_LATERITE_SOIL_AUTUMN', 'WHEAT_LATERITE_SOIL_AUTUMN', 'WHEAT', 'LATERITE_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_SALINE_SOIL_AUTUMN', 'WHEAT_SALINE_SOIL_AUTUMN', 'WHEAT', 'SALINE_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_PEATY_SOIL_AUTUMN', 'WHEAT_PEATY_SOIL_AUTUMN', 'WHEAT', 'PEATY_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_FOREST_SOIL_AUTUMN', 'WHEAT_FOREST_SOIL_AUTUMN', 'WHEAT', 'FOREST_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_SNOWFIELD_SOIL_AUTUMN', 'WHEAT_SNOWFIELD_SOIL_AUTUMN', 'WHEAT', 'SNOWFIELD_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('WHEAT_SUB_MOUNTAIN_SOIL_AUTUMN', 'WHEAT_SUB_MOUNTAIN_SOIL_AUTUMN', 'WHEAT', 'SUB_MOUNTAIN_SOIL', 'AUTUMN', 'DAILY', 1, 1, CURRENT_TIMESTAMP);






INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_RED_SOIL_AUTUMN', 'RICE_RED_SOIL_AUTUMN', 'RICE', 'RED_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_BLACK_SOIL_AUTUMN', 'RICE_BLACK_SOIL_AUTUMN', 'RICE', 'BLACK_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_ALLUVIAL_SOIL_AUTUMN', 'RICE_ALLUVIAL_SOIL_AUTUMN', 'RICE', 'ALLUVIAL_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_LATERITE_SOIL_AUTUMN', 'RICE_LATERITE_SOIL_AUTUMN', 'RICE', 'LATERITE_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_SALINE_SOIL_AUTUMN', 'RICE_SALINE_SOIL_AUTUMN', 'RICE', 'SALINE_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_PEATY_SOIL_AUTUMN', 'RICE_PEATY_SOIL_AUTUMN', 'RICE', 'PEATY_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_FOREST_SOIL_AUTUMN', 'RICE_FOREST_SOIL_AUTUMN', 'RICE', 'FOREST_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_SNOWFIELD_SOIL_AUTUMN', 'RICE_SNOWFIELD_SOIL_AUTUMN', 'RICE', 'SNOWFIELD_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

INSERT INTO SCHEDULE (SCHEDULE_NAME, DESCRIPTION, CROP_NAME, SOIL_TYPE, WEATHER_TYPE, IRRIGATION_DAY, HOURS_TO_IRRIGATE, ACTIVE_FLG, CREATED_DT) VALUES ('RICE_SUB_MOUNTAIN_SOIL_AUTUMN', 'RICE_SUB_MOUNTAIN_SOIL_AUTUMN', 'RICE', 'SUB_MOUNTAIN_SOIL', 'AUTUMN', 'BIWEEKLY', 1, 1, CURRENT_TIMESTAMP);

COMMIT;